/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiStreaksRouteImport } from './routes/api/streaks'
import { Route as ApiHabitsRouteImport } from './routes/api/habits'
import { Route as ApiCompletionsRouteImport } from './routes/api/completions'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStreaksRoute = ApiStreaksRouteImport.update({
  id: '/api/streaks',
  path: '/api/streaks',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHabitsRoute = ApiHabitsRouteImport.update({
  id: '/api/habits',
  path: '/api/habits',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCompletionsRoute = ApiCompletionsRouteImport.update({
  id: '/api/completions',
  path: '/api/completions',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/completions': typeof ApiCompletionsRoute
  '/api/habits': typeof ApiHabitsRoute
  '/api/streaks': typeof ApiStreaksRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/completions': typeof ApiCompletionsRoute
  '/api/habits': typeof ApiHabitsRoute
  '/api/streaks': typeof ApiStreaksRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/completions': typeof ApiCompletionsRoute
  '/api/habits': typeof ApiHabitsRoute
  '/api/streaks': typeof ApiStreaksRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/completions'
    | '/api/habits'
    | '/api/streaks'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api/completions' | '/api/habits' | '/api/streaks' | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/api/completions'
    | '/api/habits'
    | '/api/streaks'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiCompletionsRoute: typeof ApiCompletionsRoute
  ApiHabitsRoute: typeof ApiHabitsRoute
  ApiStreaksRoute: typeof ApiStreaksRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/streaks': {
      id: '/api/streaks'
      path: '/api/streaks'
      fullPath: '/api/streaks'
      preLoaderRoute: typeof ApiStreaksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/habits': {
      id: '/api/habits'
      path: '/api/habits'
      fullPath: '/api/habits'
      preLoaderRoute: typeof ApiHabitsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/completions': {
      id: '/api/completions'
      path: '/api/completions'
      fullPath: '/api/completions'
      preLoaderRoute: typeof ApiCompletionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiCompletionsRoute: ApiCompletionsRoute,
  ApiHabitsRoute: ApiHabitsRoute,
  ApiStreaksRoute: ApiStreaksRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
